=== wickedside/RIS/mitsoSpringHibernate/src/main/resources/clients.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mitso.com/spring/model"
           xmlns="http://www.mitso.com/spring/model"
           elementFormDefault="qualified">

    <xs:element name="clients">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="client" type="ClientType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ClientType">
        <xs:sequence>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="patronymic" type="xs:string"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
            <xs:element name="gender" type="xs:boolean"/>
            <xs:element name="passportSeries" type="xs:string"/>
            <xs:element name="passportNumber" type="xs:string"/>
            <xs:element name="identificationNumber" type="xs:string" minOccurs="0"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="actualAddress" type="xs:string"/>
            <xs:element name="homePhone" type="xs:string" minOccurs="0"/>
            <xs:element name="mobilePhone" type="xs:string" minOccurs="0"/>
            <xs:element name="registrationAddress" type="xs:string"/>
            <xs:element name="citizenship" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Определение списков городов и гражданств -->
    <xs:element name="cities">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="city" type="CityType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CityType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="citizenships">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="citizenship" type="CitizenshipType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CitizenshipType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== wickedside/RIS/mitsoSpringHibernate/src/main/resources/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns="http://www.mitso.com/spring/model"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.mitso.com/spring/model clients.xsd">
    <client>
        <surname>Иванов</surname>
        <name>Иван</name>
        <patronymic>Иванович</patronymic>
        <dateOfBirth>1990-05-15</dateOfBirth>
        <gender>true</gender>
        <passportSeries>AB</passportSeries>
        <passportNumber>123456</passportNumber>
        <identificationNumber>987654321</identificationNumber>
        <city>Минск</city>
        <actualAddress>ул. Немига, д.1</actualAddress>
        <homePhone>+375 (11) 123-45-67</homePhone>
        <mobilePhone>+375 (44) 765-43-21</mobilePhone>
        <registrationAddress>ул. Казинца, д.2</registrationAddress>
        <citizenship>Беларусь</citizenship>
    </client>
</clients>
